directories:
  output: dist
  buildResources: build
appId: com.alemayhu.notion2anki
mac:
  category: public.app-category.utilities
files:
  - filter:
      - main.js
      - dist/app.js
      - dist/index.html
      - build
      - node_modules
electronVersion: 6.1.11
